# Report Generation Utilities
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from datetime import datetime
import csv
import io

def generate_pdf_report(data, report_type, generated_by="System", subtitle=None, summary=None):
    """
    Generate PDF report with enhanced formatting
    
    Args:
        data: List of dictionaries with report data
        report_type: Type of report (e.g., "Disease History", "Yield Predictions")
        generated_by: Name of person/system generating report
        subtitle: Optional subtitle
        summary: Optional summary statistics dict
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=0.5*inch, bottomMargin=0.5*inch)
    story = []
    
    styles = getSampleStyleSheet()
    
    # Title Style
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#2c5530'),
        spaceAfter=20,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    # Subtitle Style
    subtitle_style = ParagraphStyle(
        'Subtitle',
        parent=styles['Normal'],
        fontSize=14,
        textColor=colors.HexColor('#4a7c59'),
        spaceAfter=15,
        alignment=TA_CENTER
    )
    
    # Header Style
    header_style = ParagraphStyle(
        'Header',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.grey,
        alignment=TA_CENTER
    )
    
    # Title
    title = Paragraph(f"{report_type} Report", title_style)
    story.append(title)
    
    if subtitle:
        subtitle_para = Paragraph(subtitle, subtitle_style)
        story.append(subtitle_para)
    
    # Report Info
    info_text = f"Generated by: {generated_by}<br/>Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    story.append(Paragraph(info_text, header_style))
    story.append(Spacer(1, 0.3*inch))
    
    # Summary Section
    if summary:
        summary_style = ParagraphStyle(
            'Summary',
            parent=styles['Normal'],
            fontSize=11,
            textColor=colors.HexColor('#333333'),
            spaceAfter=10
        )
        story.append(Paragraph("<b>Summary Statistics:</b>", summary_style))
        summary_data = [[k, str(v)] for k, v in summary.items()]
        summary_table = Table(summary_data, colWidths=[3*inch, 2*inch])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f0f0f0')),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (0, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        story.append(summary_table)
        story.append(Spacer(1, 0.2*inch))
    
    # Add data tables
    if isinstance(data, list) and len(data) > 0:
        if isinstance(data[0], dict):
            # Create Paragraph style for table cells
            normal_cell_style = ParagraphStyle(
                'TableCell',
                parent=styles['Normal'],
                fontSize=9,
                leading=11,
                alignment=TA_LEFT
            )
            
            header_cell_style = ParagraphStyle(
                'TableHeader',
                parent=styles['Normal'],
                fontSize=10,
                leading=12,
                textColor=colors.whitesmoke,
                fontName='Helvetica-Bold',
                alignment=TA_CENTER
            )

            # Prepare table data with Paragraphs
            headers = list(data[0].keys())
            table_data = [[Paragraph(h, header_cell_style) for h in headers]]
            
            for row in data:
                row_data = []
                for h in headers:
                    cell_text = str(row.get(h, 'N/A'))
                    # Wrap in Paragraph for auto-wrapping
                    row_data.append(Paragraph(cell_text, normal_cell_style))
                table_data.append(row_data)
            
            # Calculate column widths
            num_cols = len(headers)
            # Use nearly full width (A4 width - margins)
            # A4 width is ~595 points. Margins are 0.5 inch * 2 = 1 inch = 72 points.
            # Available width ~ 523 points.
            col_width = (A4[0] - 1.0*inch) / num_cols
            col_widths = [col_width] * num_cols
            
            # Create table
            table = Table(table_data, colWidths=col_widths, repeatRows=1)
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4a7c59')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 11),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('TOPPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.white),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('FONTSIZE', (0, 1), (-1, -1), 9),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f9f9f9')]),
            ]))
            
            story.append(KeepTogether(table))
    else:
        no_data_style = ParagraphStyle(
            'NoData',
            parent=styles['Normal'],
            fontSize=12,
            textColor=colors.grey,
            alignment=TA_CENTER
        )
        story.append(Paragraph("No data available for this report.", no_data_style))
    
    # Footer
    story.append(Spacer(1, 0.2*inch))
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.grey,
        alignment=TA_CENTER
    )
    footer_text = f"Smart Agriculture Support System - Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    story.append(Paragraph(footer_text, footer_style))
    
    # Build PDF
    doc.build(story)
    buffer.seek(0)
    return buffer

def generate_csv_report(data, report_type="Report"):
    """
    Generate CSV report using Python CSV module
    
    Args:
        data: List of dictionaries with report data
        report_type: Type of report for filename
    
    Returns:
        str: CSV formatted string
    """
    if not isinstance(data, list) or len(data) == 0:
        return "No data available"
    
    output = io.StringIO()
    
    # Write header row
    if isinstance(data[0], dict):
        fieldnames = list(data[0].keys())
        writer = csv.DictWriter(output, fieldnames=fieldnames)
        writer.writeheader()
        
        # Write data rows
        for row in data:
            # Convert all values to strings and handle None
            cleaned_row = {k: str(v) if v is not None else 'N/A' for k, v in row.items()}
            writer.writerow(cleaned_row)
    
    output.seek(0)
    return output.getvalue()

